openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:10080/backend
    description: Backend
tags:
  - name: WeatherDataController
    description: Контроллер для работы с погодными условиями
  - name: FFWIController
    description: Контроллер для работы с комплексными показателями пожарной опасности
  - name: FWIController
    description: Контроллер для работы с классом пожарной опасности
  - name: UserController
    description: Контроллер для работы с пользователями

paths:
  /api/v1/weather-data:
    get:
      tags:
        - WeatherDataController
      summary: Получить все параметры погодных условий
      description: Endpoint для получения всех погодных условий
      operationId: getWeatherDatas
      responses:
        '200':
          description: Возврат списка погодных параметров
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherDataDto'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
    post:
      tags:
        - WeatherDataController
      summary: Добавить новое погодное условие в БД
      description: Endpoint на создание нового погодного условия
      operationId: createWeatherData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWeaterDataDto'
      responses:
        '201':
          description: Успешное добавление погодного параметра
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherDataDto'
        '400':
          description: Ошибка в составлении запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example:
                  description: Пример неправильного запроса
                  value:
                    message: Название метеоданной не соответствует формату
                    code: 400
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '403':
          description: Пользователю не хватает прав
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Недостаточно прав для выполнения операции
                    code: 403
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
    patch:
      tags:
        - WeatherDataController
      summary: Обновить значение метеоданной
      description: Обновление одного из значения метеоданной
      operationId: patchWeatherData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherDataDto'
      responses:
        '200':
          description: Успешная замена полей
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherDataDto'
        '400':
          description: неправильно составлен запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Отсутствует одно из важных полей
                  value:
                    message: Отсутствует поле Id в теле запроса
                    code: 400
                example2:
                  description: Запрос составлен неправильно
                  value:
                    message: Название метеоданной не соответствует формату
                    code: 400
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '403':
          description: Пользователю не хватает прав
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Недомтаточно прав для выполнения операции
                    code: 403
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
  /api/v1/weather-data/{id}:
    parameters:
      - name: id
        required: true
        in: path
        description: Id погодного параметра
        schema:
          type: string
          format: UUID
          example: 1993dbee-eb94-46cb-aa9d-5b166b1c6659
    get:
      tags:
        - WeatherDataController
      summary: Получить конкретный погодный параметр
      description: Получение информации о погодном параметре по id
      operationId: getWeatherDataById
      responses:
        '200':
          description: Успешный ответ на запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherDataDto'
        '400':
          description: Отсутствие id в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Отсутствует параметр id в запросе
                    code: 400
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '404':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Параметр не был найден в БД
                  value:
                    message: Запись о параметре 1993dbee-eb94-46cb-aa9d-5b166b1c6659 нет в системе
                    code: 404
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
    delete:
      tags:
        - WeatherDataController
      summary: Удалить выбранный параметр
      description: Удаление выбранного параметра из системы
      operationId: deleteWeatherDataById
      responses:
        '200':
          description: Успешное удаление параметра из БД
        '400':
          description: Отсутствие в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа с отсутствием id
                  value:
                    message: Отсутствует параметр id в запросе
                    code: 400
                exmaple2:
                  description: Существует связи у параметра
                  value:
                    message: Невозможно удалить параметр Температура воздуха. Он связан с другими записями
                    code: 400
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '403':
          description: Пользователю не хватает прав
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Недостаточно прав для выполнения операции
                    code: 403
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500

  /api/v1/fire-forecast-indexes:
    get:
      tags:
        - FFWIController
      summary: Endpoint для получения всей информации об КППО
      description: Получение списка КППО для отображения на странице
      operationId: getAllFfwi
      responses:
        '200':
          description: Успешный ответ на запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FFWIResponseDto'
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
    post:
      tags:
        - FFWIController
      summary: Endpoint для добавления нового КППО
      description: Добавление КППО в базу данных
      operationId: createFfwi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FFWICreateRequestDto'
            examples:
              example1:
                value:
                  name: КППО Свердловой
                  formula: $K_v * ($T_d - $T_o) * $T_d
                  weatherDataParams:
                    - id: 28723f7b-7798-4e34-9569-e46a255aab3d
                      formulaParameter: $K_v
                    - id: 28723f7b-7798-4e34-9569-e46a255aab3d
                      formulaParameter: $T_d
                    - id: 28723f7b-7798-4e34-9569-e46a255aab3d
                      formulaParameter: $T_o

      responses:
        '201':
          description: Успешное создание КППО
        '400':
          description: Ошибка в составлении запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример неправильного запроса
                  value:
                    message: Название КППО не соответствует формату
                    code: 400
                example2:
                  description: Формула не соответствует грамматике
                  value:
                    message: Формула не соответствует грамматике
                    code: 400
        '401':
          description: Пользователь не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Пользователь не авторизован
                    code: 401
        '403':
          description: Пользователю не хватает прав
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Пример ответа
                  value:
                    message: Недостаточно прав для выполнения операции
                    code: 403
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500

  /api/v1/users/login:
    post:
      tags:
        - UserController
      summary: Endpoint для аутентификации пользователя в системе
      description: Аутентификация пользователя в приложении
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginDto'
      responses:
        '200':
          description: Успешная аутентификация пользователя в системе
        '400':
          description: Ошибка в составлении запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример неправильного запроса_1
                  value:
                    message: В логине встретился неподдерживаемый символ
                    code: 400
        '404':
          description: Пользователь не найден в приложении по username или паролю
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                exmaple1:
                  description: Запись о пользователе с логином/почтой или паролем не найдена
                  value:
                    message: Пользователь с такими данными не найден в системе
                    code: 404
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500
  /api/v1/users/registration:
    post:
      tags:
        - UserController
      summary: Endpoint для регистрации пользователя в системе
      description: Регистрация нового пользователя в приложении
      operationId: registrateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateDto'
      responses:
        '201':
          description: Успешная регистрация пользователя
        '400':
          description: Ошибка в составлении запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример неправильного запроса_1
                  value:
                    message: В логине встретился неподдерживаемый символ
                    code: 400
                example2:
                  description: Пример неправильного запроса_2
                  value:
                    message: Код регистрации истёк
                    code: 400
        '500':
          description: Ошибка на сервере
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionDto'
              examples:
                example1:
                  description: Пример ответа на 500
                  value:
                    message: Произошла ошибка на стороне сервера
                    code: 500


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # DTO для погодных параметров
    ApiExceptionDto:
      type: object
      description: ДТО для ответа с ошибкой
      required:
        - code
        - message
      properties:
        message:
          type: string
          description: Сообщение с ошибкой
        code:
          type: integer
          format: int32
    WeatherDataDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 1993dbee-eb94-46cb-aa9d-5b166b1c6659
          description: ID погодного параметра в системе
        name:
          type: string
          example: Температура воздуха
          description: Название погодного параметра
    CreateWeaterDataDto:
      type: object
      description: ДТО на добавление новго погодного условия
      required:
        - name
      properties:
        name:
          type: string
          example: Температура воздуха
    # DTO для КППО
    FFWIResponseDto:
      description: DTO представления КППО в приложении
      properties:
        ffwiId:
          type: string
          description: ID КППО
          format: uuid
          example: 92eb322f-9fec-4f5c-adbf-008627ed271a
        name:
          type: string
          description: Название КППО
          example: КППО Нестерова
        formula:
          type: string
          description: Формула определения КП
          example: ($T_d - $T_0) * $T_d
        fwis:
          type: string
          description: Список названий КПО, придлежащих КППО
          example: КПО_Нестеров_1, КПО_Нестеров_2, КПО_Нестеров_3
        weatherParams:
          type: array
          items:
            $ref: '#/components/schemas/FFWIWeatherParamDto'
        precipitationTableParams:
          type: array
          items:
            type: object
            properties:
              fireRange:
                type: string
                description: Диапазон горимости
                example: [0, ∞]
              precipitation:
                type: integer
                description: Кол-во осадков для сброса
                example: 3
    FFWIWeatherParamDto:
      description: Представление погодного параметра с параметром, связывающим формулу
      properties:
        id:
          type: string
          description: ID погодного параметра
          example: 2a3c6c0e-2d26-49fb-ab45-55a3e703cace
        weatherName:
          type: string
          description: Название погодного условия
          example: Температура воздуха
        formulaParameter:
          type: string
          description: Название параметра в формуле
          example: $T_d
    FFWICreateRequestDto:
      description: DTO для создания КППО
      required:
        - name
        - formula
        - weatherDataIds
      properties:
        name:
          type: string
          description: Название КППО
          example: КППО Свердловой
        formula:
          type: string
          description: Формула определения КП
          example: ($T_d - $T_0) * $T_d
        weatherDataParams:
          type: array
          items:
            $ref: '#/components/schemas/FFWIWeatherParamDto'


    # DTO для пользователя
    UserCreateDto:
      type: object
      description: DTO для создания пользователя
      required:
        - registrationCode
        - login
        - password
        - email
      properties:
        registrationCode:
          type: string
          description: Код регистрации пользователя
          format: uuid
          example: 7894a71a-0c58-4ee0-9ed7-283ae4ce54ae
        login:
          type: string
          description: Логин пользователя
          example: tcvetkov.so
        password:
          type: string
          description: Пароль пользователя
          example: $omeP@ssw0rd
        email:
          type: string
          description: Email адрес пользователя
          format: email
          example: tsvetkov@so@dvfu.ru
    UserLoginDto:
      type: object
      description: DTO для логина пользователя
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: Логин или почта пользователя
          example: tcvetkov.so
        password:
          type: string
          description: Пароль пользователя
          example: $omeP@ssw0rd
